stages:
  - test
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: parties
  IMAGE_TAG: $CI_COMMIT_TAG || $CI_COMMIT_SHA

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml


build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG ./
  only:
    - main

push:
  stage: push
  image: docker
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main