stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY/eureka-poker-web/service-parties
  IMAGE_TAG: $CI_COMMIT_SHA

build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "Pushing image"
    - echo $CI_COMMIT_TAG
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - docker info

  stage: build
  script:
    - docker build -t $IMAGE_NAME:IMAGE_TAG .
    - docker push $IMAGE_NAME:IMAGE_TAG

  only:
    - main

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']

  script:
    - echo "Settings config for kubectl"
    - kubectl config get-contexts
    - kubectl config use-context eureka-poker-web/pipelines:prod-agent
    - kubectl get pods

    - echo "Applying Kubernetes manifests"
    - sed -i "s@{{IMAGE_NAME}}@$IMAGE_NAME@g" kube/deployment.yml
    - sed -i "s@{{IMAGE_TAG}}@IMAGE_TAG@g" kube/deployment.yml
    - kubectl apply -f kube/deployment.yml
    - kubectl apply -f kube/service.yml
    - kubectl rollout status deployment/parties-deployment

  only:
    - main
