default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - docker info

stages:
  - test
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY/eureka-poker-web/service-parties
  IMAGE_TAG: $CI_COMMIT_SHA

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .

  only:
    - main

push:
  stage: push
  script:
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main