# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- build
- push

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: registry.gitlab.com/username/frontend-repo
  IMAGE_TAG: $CI_COMMIT_TAG || $CI_COMMIT_SHA

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG ./
  only:
    - main

push:
  stage: push
  script:
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main
