stages:
  - test
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: parties
  IMAGE_TAG: $CI_COMMIT_TAG || $CI_COMMIT_SHA

sast:
  stage: test
  image: registry.gitlab.com/security-products/semgrep:5
  script:
    - semgrep --config .semgrep.yml ./

build:
  stage: build
  image: $CI_REGISTRY/group/project/docker:20.10.16
  services:
    - name: $CI_REGISTRY/group/project/docker:20.10.16-dind
      alias: docker
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG ./
  only:
    - main

push:
  stage: push
  image: $CI_REGISTRY/group/project/docker:20.10.16
  services:
    - name: $CI_REGISTRY/group/project/docker:20.10.16-dind
      alias: docker
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main